# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  backendapi:
    container_name: backendapi
    #image: backendapi:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: 'data_web'
      #DATABASE_USER: # DATABASE_USER
      #DATABASE_PASS: # DATABASE_PASS
      DATABASE_URL: 'mongodb://database:27017/'
    ports:
      - '8088:8088'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: # DATABASE_NAME
    #   MONGO_INITDB_ROOT_PASSWORD: # DATABASE_USER